In [2]:
import numpy as np



[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>


In [5]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2)
print(type(arr))

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [6]:
arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [3]:
print(np.__version__)

2.4.2


In [7]:
arr5 = np.array([1.1, 2.1, 3.1])

newarr = arr5.astype('i')

print(newarr)
print(newarr.dtype)


[1 2 3]
int32
[1 2 3]
